/* tslint:disable */
/* eslint-disable */
/**
 * Final project\'s back-end API
 * Back-end API for final-project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateStripePriceDto
 */
export interface CreateStripePriceDto {
    /**
     * 
     * @type {string}
     * @memberof CreateStripePriceDto
     */
    'currency': string;
    /**
     * 
     * @type {number}
     * @memberof CreateStripePriceDto
     */
    'product': number;
    /**
     * 
     * @type {number}
     * @memberof CreateStripePriceDto
     */
    'unit_amount': number;
}

