/* tslint:disable */
/* eslint-disable */
/**
 * Final project\'s back-end API
 * Back-end API for final-project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateOrderDto
 */
export interface CreateOrderDto {
    /**
     * 
     * @type {object}
     * @memberof CreateOrderDto
     */
    'userId': object;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrderDto
     */
    'productsId': Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CreateOrderDto
     */
    'paymentId': object;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderDto
     */
    'status': string;
}

