/* tslint:disable */
/* eslint-disable */
/**
 * Final project\'s back-end API
 * Back-end API for final-project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateRatingDto
 */
export interface CreateRatingDto {
    /**
     * 
     * @type {number}
     * @memberof CreateRatingDto
     */
    'rating': number;
    /**
     * 
     * @type {object}
     * @memberof CreateRatingDto
     */
    'productId': object;
    /**
     * 
     * @type {object}
     * @memberof CreateRatingDto
     */
    'userId': object;
}

