/* tslint:disable */
/* eslint-disable */
/**
 * Final project\'s back-end API
 * Back-end API for final-project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateProductDto
 */
export interface UpdateProductDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductDto
     */
    'stripeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductDto
     */
    'title'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProductDto
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductDto
     */
    'brand'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductDto
     */
    'rating'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProductDto
     */
    'categories'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductDto
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductDto
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductDto
     */
    'stock'?: number;
}

