/* tslint:disable */
/* eslint-disable */
/**
 * Final project\'s back-end API
 * Back-end API for final-project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePaymentDto
 */
export interface UpdatePaymentDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePaymentDto
     */
    'paymentIntentId'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdatePaymentDto
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePaymentDto
     */
    'method'?: string;
}

