/* tslint:disable */
/* eslint-disable */
/**
 * Final project\'s back-end API
 * Back-end API for final-project
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateOrderDto
 */
export interface UpdateOrderDto {
    /**
     * 
     * @type {object}
     * @memberof UpdateOrderDto
     */
    'userId'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateOrderDto
     */
    'productsId'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof UpdateOrderDto
     */
    'paymentId'?: object;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrderDto
     */
    'status'?: string;
}

